-- =====================================================================
-- Festival Karakter Pelajar Universitas STEKOM
-- Migration 0001 — Schema, constraints, indexes
-- =====================================================================

-- Extensions ----------------------------------------------------------
create extension if not exists "pgcrypto";   -- gen_random_uuid()

-- =====================================================================
-- SCHOOLS
-- =====================================================================
create table if not exists public.schools (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  created_at  timestamptz not null default now()
);

-- =====================================================================
-- PROFILES (1:1 with auth.users)
--  - voter   : passwordless, created via Supabase anonymous auth
--  - admin   : password (hash stored here), seeded
--  - participant: password generated by admin on creation
-- =====================================================================
create table if not exists public.profiles (
  id                  uuid primary key references auth.users(id) on delete cascade,
  name                text not null,
  phone_number        text not null unique,
  school_id           uuid references public.schools(id) on delete set null,
  role                text not null default 'voter'
                        check (role in ('admin', 'participant', 'voter')),
  device_fingerprint  text,
  created_at          timestamptz not null default now()
);

create index if not exists idx_profiles_school on public.profiles(school_id);
create index if not exists idx_profiles_role   on public.profiles(role);

-- =====================================================================
-- PARTICIPANTS (contestants — entity managed by admin, linked to a profile)
-- =====================================================================
create table if not exists public.participants (
  id            uuid primary key default gen_random_uuid(),
  profile_id    uuid unique references public.profiles(id) on delete set null,
  name          text not null,
  school_id     uuid not null references public.schools(id) on delete restrict,
  photo_url     text,
  description   text,
  total_points  integer not null default 0,
  status        text not null default 'active' check (status in ('active', 'inactive')),
  created_at    timestamptz not null default now()
);

create index if not exists idx_participants_school on public.participants(school_id);
create index if not exists idx_participants_points on public.participants(total_points desc);

-- =====================================================================
-- USER_DEVICES — 1 device fingerprint bound to exactly one account.
-- A second account from the same device is rejected at vote time.
-- =====================================================================
create table if not exists public.user_devices (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.profiles(id) on delete cascade,
  device_fingerprint  text not null,
  server_hash         text,
  created_at          timestamptz not null default now(),
  unique (device_fingerprint)        -- one device -> one primary account
);

create index if not exists idx_user_devices_user on public.user_devices(user_id);

-- =====================================================================
-- QUESTS
-- =====================================================================
create table if not exists public.quests (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  description  text,
  point        integer not null default 0,
  status       text not null default 'active' check (status in ('active', 'inactive')),
  created_at   timestamptz not null default now()
);

-- =====================================================================
-- SUBMISSIONS — quest proof uploads, approved by admin
-- =====================================================================
create table if not exists public.submissions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.profiles(id) on delete cascade,
  participant_id  uuid not null references public.participants(id) on delete cascade,
  quest_id        uuid not null references public.quests(id) on delete cascade,
  proof_url       text not null,
  status          text not null default 'pending'
                    check (status in ('pending', 'approved', 'rejected')),
  created_at      timestamptz not null default now()
);

create index if not exists idx_submissions_status      on public.submissions(status);
create index if not exists idx_submissions_user        on public.submissions(user_id);
create index if not exists idx_submissions_participant on public.submissions(participant_id);

-- =====================================================================
-- DAILY_VOTES — +5 points / day.
-- Dual uniqueness is the core anti-cheat:
--   (user_id, vote_date)            => one account can vote once/day
--                                      even if it switches devices.
--   (device_fingerprint, vote_date) => one device can vote once/day
--                                      even if it switches accounts.
-- =====================================================================
create table if not exists public.daily_votes (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.profiles(id) on delete cascade,
  participant_id      uuid not null references public.participants(id) on delete cascade,
  device_fingerprint  text not null,
  server_hash         text,
  vote_date           date not null default current_date,
  created_at          timestamptz not null default now(),
  unique (user_id, vote_date),
  unique (device_fingerprint, vote_date)
);

create index if not exists idx_daily_votes_participant on public.daily_votes(participant_id);
create index if not exists idx_daily_votes_date        on public.daily_votes(vote_date);
create index if not exists idx_daily_votes_user        on public.daily_votes(user_id);

-- =====================================================================
-- STORAGE BUCKETS
-- =====================================================================
insert into storage.buckets (id, name, public)
values
  ('participant-photos', 'participant-photos', true),
  ('quest-proofs',       'quest-proofs',       true)
on conflict (id) do nothing;
